### PR TITLE
Update url and regex for EasyFind

### PR DESCRIPTION
**Pull request by aschwanb**

### CODE REVIEW

**Comment by aschwanb** [comment]
Hey @onecooltaco 

The URLs for EasyFind changed. This PR should address the change.

Best regards

**Comment by cwhits** [comment]
Works for me! Please merge @onecooltaco :)

```
cwhits at its-ees1502 in ~/git/jleggat-recipes/EasyFind
$ autopkg run -v EasyFind.download.recipe     
Processing EasyFind.download.recipe...
WARNING: EasyFind.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
URLTextSearcher: Found matching text (match): https://s3.amazonaws.com/DTWebsiteSupport/download/freeware/easyfind/4.9.3/EasyFind.app.zip
URLDownloader
URLDownloader: Storing new Last-Modified header: Thu, 17 Jul 2014 06:23:43 GMT
URLDownloader: Storing new ETag header: "38c811eb79b5ff3b8b74c0f4c4f16ad5"
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.jleggat.EasyFind.download/downloads/EasyFind.zip
EndOfCheckPhase
Unarchiver
Unarchiver: Guessed archive format 'zip' from filename EasyFind.zip
Unarchiver: Unarchived /Users/cwhits/Library/AutoPkg/Cache/com.github.jleggat.EasyFind.download/downloads/EasyFind.zip to /Users/cwhits/Library/AutoPkg/Cache/com.github.jleggat.EasyFind.download/EasyFind
CodeSignatureVerifier
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: /Users/cwhits/Library/AutoPkg/Cache/com.github.jleggat.EasyFind.download/EasyFind/EasyFind.app: valid on disk
CodeSignatureVerifier: /Users/cwhits/Library/AutoPkg/Cache/com.github.jleggat.EasyFind.download/EasyFind/EasyFind.app: satisfies its Designated Requirement
CodeSignatureVerifier: /Users/cwhits/Library/AutoPkg/Cache/com.github.jleggat.EasyFind.download/EasyFind/EasyFind.app: explicit requirement satisfied
CodeSignatureVerifier: Signature is valid
Receipt written to /Users/cwhits/Library/AutoPkg/Cache/com.github.jleggat.EasyFind.download/receipts/EasyFind.download-receipt-20190401-084212.plist

The following new items were downloaded:
    Download Path                                                                                    
    -------------                                                                                    
    /Users/cwhits/Library/AutoPkg/Cache/com.github.jleggat.EasyFind.download/downloads/EasyFind.zip  

```

**Comment by cwhits** [comment]
Also, this fixes #68 :)

**Comment by aschwanb** [comment]
Thanks 👍

**Pull request merged**
